### PR TITLE
[WIP] Material Design

### PR DESCRIPTION
**Pull request by librehat**
Start/Stop functionality needs to be fixed.
There are also four errors in inspector console.

### CODE REVIEW

**Comment by meowlab** [comment]
Thanks!
Maybe we should implement start/stop server before merge?
And once I have spare time I will took a look on those errors

**Comment by librehat** [comment]
I don't know how to implement that... Plus I couldn't start the server on my chromebook.

**Comment by meowlab** [comment]
For four errors in console:
Change `app.js` to suppress first error
```javascript
angular.module('shadowsocks', ['ngMaterial'], function($provide) {
  // Suppress "history.pushState is not available in packaged apps."
  $provide.decorator('$window', function($delegate) {
    $delegate.history = null;
    return $delegate;
  });
});
```
And another three error is because you miss `/` in `ng-pattern`, the correct one should be `/^[0-9]+$/`

**Comment by librehat** [comment]
I clicked merge by a mistake. Now the master branch is restored in the repository. This pull request is abandoned.

**Pull request merged**
